const Error = error{
    unexpected_result,
};

const main = fn () Error!void {
    const a: [4]u8 = .{1, 2, 3, 4};
    const b: []const []const u8 = .{a.&}.&;
    const c: u8 = b[0][0] - 1;
    if (c != 0) {
        return Error.unexpected_result;
    }
}
